name: eleventy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: get last sha
        run: echo "LAST_COMMIT=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: ayeressian/bunnycdn-storage-deploy@v1.1.1
        with:
          storageEndpoint: "sg.storage.bunnycdn.com"
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          accessKey: "${{ secrets.STORAGE_KEY }}"
          source: "dist"
          remove: "true"
          purge: "false"
      - name: Deploy (GH pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: rizaldy.today
